name: baseball_analysis
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3.5
  - tensorflow=1.4.0
  - numpy=1.12.1
  - opencv=3.3.0
  - scipy=0.19.1
  - scikit-learn=0.19.0
  - matplotlib>=2.0.2
  - pytorch=0.3.0
  - pandas=0.22.0
  - pip
  - pip:
    - tensorflow-tensorboard>=0.1.5
